FROM ubuntu:latest

# Temel bağımlılıkları yükleyelim
RUN apt-get update && \
    apt-get install -y python3 openssh-server && \
    apt-get clean

# SSH sunucusunu yapılandırma
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# SSH anahtarlarını yerleştirme
RUN mkdir -p /root/.ssh
COPY id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

EXPOSE 22 80

CMD ["/usr/sbin/sshd", "-D"]
