FROM ubuntu:20.04

# Temel bağımlılıkları yükleyelim
RUN apt-get update && \
    apt-get install -y python3 python3-pip openssh-client ansible && \
    apt-get clean

# SSH anahtarlarını oluşturma ve yerleştirme
RUN mkdir /root/.ssh
COPY id_rsa /root/.ssh/id_rsa
COPY id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 600 /root/.ssh/id_rsa /root/.ssh/id_rsa.pub

# Ansible konfigürasyon dosyalarını kopyalama
COPY ansible.cfg /etc/ansible/ansible.cfg
COPY inventory /etc/ansible/hosts
COPY playbook.yml /etc/ansible/playbook.yml

# SSH sunucusunu yapılandırma (isteğe bağlı)
RUN apt-get install -y openssh-server && \
    mkdir /var/run/sshd && \
    echo 'root:password' | chpasswd && \
    sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
