---
- name: Setup managed nodes
  hosts: managed_nodes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes

    - name: Create index.html
      copy:
        dest: /var/www/html/index.html
        content: "<html><body><h1>Hello from Ansible</h1></body></html>"
      become: yes

    - name: Start Nginx
      service:
        name: nginx
        state: started

